# Start your image with a node base image
FROM node:18-alpine

# The /app directory should act as the main application directory
WORKDIR /app

# Copy the app package and package-lock.json file
COPY package*.json ./

# Install node packages
RUN npm install --legacy-peer-deps

# Install serve globally
RUN npm install -g serve

# Copy the rest of the application code
COPY . .

# Build the app
RUN npm run build

# Remove development dependencies
RUN rm -fr node_modules

EXPOSE 3000

# Start the app using serve command
CMD ["serve", "-s", "build"]
