version: "3"
services:

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: connectLoom
      MONGO_INITDB_ROOT_PASSWORD: connectLoom
    networks:
      - app-network


  # API (backend) service
  api:
    image: sarathchandran2000/connectloom-backendserver:latest
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network

 
  # Frontend service
  frontend:
    image: sarathchandran2000/connectloom-frontend-ui:latest
    container_name: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

  # NGINX service
  nginx:
    image: sarathchandran2000/connectloom-nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

  
